### ISSUE TITLE
Python module gi.repository.Gtk          : not found  Could not find the python module 'gi.repository.Gtk'

### ISSUE THREAD

**Issue by SolarAquarion** [kupferlauncher/kupfer#111]

**Comment by khurshid-alam** [comment]
simply missing packages. If you are on Ubuntu make sure `gir1.2-gtk-3.0` is installed.

**Comment by canicola** [comment]
I have a similar issue, even with installing` gir1.2-gtk-3.0 `I get the following error message.

```
canicola@thinkpad:~/$ kupfer
Kupfer: A free software (GPLv3+) launcher
   Copyright © 2007–2017 Ulrik Sverdrup with others
   https://kupferlauncher.github.io/

Traceback (most recent call last):
  File "/usr/share/kupfer/kupfer.py", line 22, in <module>
    main.main()
  File "/usr/share/kupfer/kupfer/main.py", line 177, in main
    gtkmain(browser_start, quiet)
  File "/usr/share/kupfer/kupfer/main.py", line 142, in gtkmain
    import gi
ModuleNotFoundError: No module named 'gi'
```

**Comment by khurshid-alam** [comment]
You need to install python3-gu

**Comment by khurshid-alam** [comment]
You need to install python3-gu
