### ISSUE TITLE
Kupfer not starting anymore

### ISSUE THREAD

**Issue by rgarcia89** [kupferlauncher/kupfer#112]
Please provide enough information to reproduce the issue.

### Environment

Kupfer Version:
Installed Packages
Name         : kupfer
Version      : 208
Release      : 15.fc28
Arch         : noarch
Size         : 3.7 M
Source       : kupfer-208-15.fc28.src.rpm
Repo         : @System
From repo    : fedora

Window Manager: Gnome
Linux Distribution:
Linux raulgs-xm1 4.16.16-300.fc28.x86_64 #1 SMP Sun Jun 17 03:02:42 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Actual Behaviour
Kupfer is not starting anymore

```Traceback (most recent call last):
  File "/usr/share/kupfer/kupfer.py", line 21, in <module>
    from kupfer import main
  File "/usr/share/kupfer/kupfer/main.py", line 33, in <module>
    setup_locale_and_gettext()
  File "/usr/share/kupfer/kupfer/main.py", line 21, in setup_locale_and_gettext
    names=("ngettext",))
TypeError: install() got an unexpected keyword argument 'unicode'
```
This is happening science I installed the latest OS updates.

List of packages updated this morning:
```
totem-nautilus-3.26.1-1.fc28.x86_64           Fr 22 Jun 2018 08:55:08 CEST
qemu-guest-agent-2.11.1-3.fc28.x86_64         Fr 22 Jun 2018 08:55:08 CEST
python3-texttable-1.3.1-1.fc28.noarch         Fr 22 Jun 2018 08:55:08 CEST
python3-brlapi-0.6.7-19.fc28.x86_64           Fr 22 Jun 2018 08:55:08 CEST
libvirt-daemon-kvm-4.1.0-3.fc28.x86_64        Fr 22 Jun 2018 08:55:08 CEST
libvirt-client-4.1.0-3.fc28.x86_64            Fr 22 Jun 2018 08:55:08 CEST
libvirt-4.1.0-3.fc28.x86_64                   Fr 22 Jun 2018 08:55:08 CEST
flatpak-libs-0.11.8.3-1.fc28.x86_64           Fr 22 Jun 2018 08:55:08 CEST
flatpak-0.11.8.3-1.fc28.x86_64                Fr 22 Jun 2018 08:55:08 CEST
totem-3.26.1-1.fc28.x86_64                    Fr 22 Jun 2018 08:55:07 CEST
libvirt-daemon-driver-xen-4.1.0-3.fc28.x86_64 Fr 22 Jun 2018 08:55:07 CEST
libvirt-bash-completion-4.1.0-3.fc28.x86_64   Fr 22 Jun 2018 08:55:07 CEST
qemu-system-x86-core-2.11.1-3.fc28.x86_64     Fr 22 Jun 2018 08:55:06 CEST
qemu-system-x86-2.11.1-3.fc28.x86_64          Fr 22 Jun 2018 08:55:06 CEST
qemu-kvm-2.11.1-3.fc28.x86_64                 Fr 22 Jun 2018 08:55:06 CEST
qemu-block-ssh-2.11.1-3.fc28.x86_64           Fr 22 Jun 2018 08:55:06 CEST
qemu-block-rbd-2.11.1-3.fc28.x86_64           Fr 22 Jun 2018 08:55:06 CEST
qemu-block-nfs-2.11.1-3.fc28.x86_64           Fr 22 Jun 2018 08:55:06 CEST
qemu-block-iscsi-2.11.1-3.fc28.x86_64         Fr 22 Jun 2018 08:55:06 CEST
qemu-block-gluster-2.11.1-3.fc28.x86_64       Fr 22 Jun 2018 08:55:06 CEST
qemu-block-dmg-2.11.1-3.fc28.x86_64           Fr 22 Jun 2018 08:55:06 CEST
qemu-block-curl-2.11.1-3.fc28.x86_64          Fr 22 Jun 2018 08:55:06 CEST
libvirt-daemon-driver-vbox-4.1.0-3.fc28.x86_64 Fr 22 Jun 2018 08:55:06 CEST
libvirt-daemon-driver-uml-4.1.0-3.fc28.x86_64 Fr 22 Jun 2018 08:55:06 CEST
libvirt-daemon-driver-lxc-4.1.0-3.fc28.x86_64 Fr 22 Jun 2018 08:55:06 CEST
libvirt-daemon-driver-libxl-4.1.0-3.fc28.x86_64 Fr 22 Jun 2018 08:55:06 CEST
libvirt-daemon-config-nwfilter-4.1.0-3.fc28.x86_64 Fr 22 Jun 2018 08:55:06 CEST
libvirt-daemon-config-network-4.1.0-3.fc28.x86_64 Fr 22 Jun 2018 08:55:06 CEST
libvirt-daemon-driver-storage-zfs-4.1.0-3.fc28.x86_64 Fr 22 Jun 2018 08:55:05 CEST
libvirt-daemon-driver-storage-sheepdog-4.1.0-3.fc28.x86_64 Fr 22 Jun 2018 08:55:05 CEST
libvirt-daemon-driver-storage-scsi-4.1.0-3.fc28.x86_64 Fr 22 Jun 2018 08:55:05 CEST
libvirt-daemon-driver-storage-rbd-4.1.0-3.fc28.x86_64 Fr 22 Jun 2018 08:55:05 CEST
libvirt-daemon-driver-storage-mpath-4.1.0-3.fc28.x86_64 Fr 22 Jun 2018 08:55:05 CEST
libvirt-daemon-driver-storage-logical-4.1.0-3.fc28.x86_64 Fr 22 Jun 2018 08:55:05 CEST
libvirt-daemon-driver-storage-4.1.0-3.fc28.x86_64 Fr 22 Jun 2018 08:55:05 CEST
qemu-img-2.11.1-3.fc28.x86_64                 Fr 22 Jun 2018 08:55:04 CEST
libvirt-daemon-driver-storage-iscsi-4.1.0-3.fc28.x86_64 Fr 22 Jun 2018 08:55:04 CEST
libvirt-daemon-driver-storage-gluster-4.1.0-3.fc28.x86_64 Fr 22 Jun 2018 08:55:04 CEST
libvirt-daemon-driver-storage-disk-4.1.0-3.fc28.x86_64 Fr 22 Jun 2018 08:55:04 CEST
libvirt-daemon-driver-storage-core-4.1.0-3.fc28.x86_64 Fr 22 Jun 2018 08:55:04 CEST
libvirt-daemon-driver-secret-4.1.0-3.fc28.x86_64 Fr 22 Jun 2018 08:55:04 CEST
libvirt-daemon-driver-qemu-4.1.0-3.fc28.x86_64 Fr 22 Jun 2018 08:55:04 CEST
libvirt-daemon-driver-nodedev-4.1.0-3.fc28.x86_64 Fr 22 Jun 2018 08:55:04 CEST
libvirt-daemon-driver-interface-4.1.0-3.fc28.x86_64 Fr 22 Jun 2018 08:55:04 CEST
brlapi-0.6.7-19.fc28.x86_64                   Fr 22 Jun 2018 08:55:04 CEST
qemu-common-2.11.1-3.fc28.x86_64              Fr 22 Jun 2018 08:55:03 CEST
libvirt-daemon-driver-nwfilter-4.1.0-3.fc28.x86_64 Fr 22 Jun 2018 08:55:03 CEST
libvirt-daemon-driver-network-4.1.0-3.fc28.x86_64 Fr 22 Jun 2018 08:55:03 CEST
brltty-5.6-19.fc28.x86_64                     Fr 22 Jun 2018 08:55:03 CEST
libvirt-libs-4.1.0-3.fc28.x86_64              Fr 22 Jun 2018 08:55:02 CEST
libvirt-daemon-4.1.0-3.fc28.x86_64            Fr 22 Jun 2018 08:55:02 CEST
atom-1.28.0-0.1.x86_64                        Fr 22 Jun 2018 08:54:48 CEST
```

**Comment by khurshid-alam** [comment]
208 is old version with python2. It won't work in newer fedora. Use new version or compile yourself.

**Comment by rgarcia89** [comment]
so right. I just complied and installed the latest version. Thanks a lot.
