### ISSUE TITLE
Cannot open preferences window

### ISSUE THREAD

**Issue by dcelasun** [kupferlauncher/kupfer#23]
Another v300 issue:

```
Traceback (most recent call last):
  File "/usr/share/kupfer/kupfer/ui/browser.py", line 1973, in mitem_handler
    callback(ui_ctx)
  File "/usr/share/kupfer/kupfer/kupferui.py", line 62, in show_preferences
    win = preferences.GetPreferencesWindowController()
  File "/usr/share/kupfer/kupfer/ui/preferences.py", line 911, in GetPreferencesWindowController
    _preferences_window = PreferencesWindowController()
  File "/usr/share/kupfer/kupfer/ui/preferences.py", line 170, in __init__
    key= lambda rec: rec["localized_name"])
  File "/usr/share/kupfer/kupfer/utils.py", line 79, in locale_sort
    seq = seq if isinstance(seq, list) else list(seq)
  File "/usr/share/kupfer/kupfer/core/plugins.py", line 62, in get_plugin_info
    plugin = import_plugin_any(plugin_name)
  File "/usr/share/kupfer/kupfer/core/plugins.py", line 275, in import_plugin_any
    return _staged_import(name, _import_hook_fake)
  File "/usr/share/kupfer/kupfer/core/plugins.py", line 252, in _staged_import
    plugin = import_hook(_plugin_path(name))
  File "/usr/share/kupfer/kupfer/core/plugins.py", line 206, in _import_hook_fake
    return _import_plugin_fake(modpath)
  File "/usr/share/kupfer/kupfer/core/plugins.py", line 195, in _import_plugin_fake
    code = _truncate_code(code, info_attributes)
  File "/usr/share/kupfer/kupfer/core/plugins.py", line 159, in _truncate_code
    global_name = code.co_names[num]
IndexError: tuple index out of range
```

**Comment by engla** [comment]
Python version?

**Comment by dcelasun** [comment]
3.6.0

**Comment by engla** [comment]
Thank you. I realized it must be related to some particular plugin. I'm sorry that this fake plugin loader is particularly insane. I think it will just have something to catch the error and log it (and skip the plugin) for now.

**Comment by dcelasun** [comment]
Sounds good. Can you also tag a new release (like v300.1) so I can update the package?

**Comment by engla** [comment]
It would be super cool if you could test master before the release

**Comment by engla** [comment]
(Just updated)

**Comment by dcelasun** [comment]
Much better, thanks! Now, the failing plugins are just spamming the console, but the preferences window can be opened.

```
Error [kupfer.core.plugins]: Could not load 'archiveinside'
Exception in [tuple index out of range]: IndexError: tuple index out of range
Error [kupfer.core.plugins]: Could not load 'audacious'
Exception in [tuple index out of range]: IndexError: tuple index out of range
Error [kupfer.core.plugins]: Could not load 'custom_terminal'
Exception in [tuple index out of range]: IndexError: tuple index out of range
Error [kupfer.core.plugins]: Could not load 'defaultmail'
Exception in [tuple index out of range]: IndexError: tuple index out of range
Error [kupfer.core.plugins]: Could not load 'duckduckgo'
Exception in [tuple index out of range]: IndexError: tuple index out of range
Error [kupfer.core.plugins]: Could not load 'glob'
Exception in [tuple index out of range]: IndexError: tuple index out of range
Error [kupfer.core.plugins]: Could not load 'higherorder'
Exception in [tuple index out of range]: IndexError: tuple index out of range
Error [kupfer.core.plugins]: Could not load 'image'
Exception in [tuple index out of range]: IndexError: tuple index out of range
Error [kupfer.core.plugins]: Could not load 'kupfer_plugins'
Exception in [tuple index out of range]: IndexError: tuple index out of range
Error [kupfer.core.plugins]: Could not load 'notes'
Exception in [tuple index out of range]: IndexError: tuple index out of range
Error [kupfer.core.plugins]: Could not load 'quickview'
Exception in [tuple index out of range]: IndexError: tuple index out of range
Error [kupfer.core.plugins]: Could not load 'screen'
Exception in [tuple index out of range]: IndexError: tuple index out of range
Error [kupfer.core.plugins]: Could not load 'sendkeys'
Exception in [tuple index out of range]: IndexError: tuple index out of range
Error [kupfer.core.plugins]: Could not load 'session_xfce'
Exception in [tuple index out of range]: IndexError: tuple index out of range
Error [kupfer.core.plugins]: Could not load 'ssh_hosts'
Exception in [tuple index out of range]: IndexError: tuple index out of range
Error [kupfer.core.plugins]: Could not load 'templates'
Exception in [tuple index out of range]: IndexError: tuple index out of range
Error [kupfer.core.plugins]: Could not load 'textfiles'
Exception in [tuple index out of range]: IndexError: tuple index out of range
Error [kupfer.core.plugins]: Could not load 'thunar'
Exception in [tuple index out of range]: IndexError: tuple index out of range
Error [kupfer.core.plugins]: Could not load 'thunderbird'
Exception in [tuple index out of range]: IndexError: tuple index out of range
Error [kupfer.core.plugins]: Could not load 'top'
Exception in [tuple index out of range]: IndexError: tuple index out of range
Error [kupfer.core.plugins]: Could not load 'tracker1'
Exception in [tuple index out of range]: IndexError: tuple index out of range
Error [kupfer.core.plugins]: Could not load 'windows'
Exception in [tuple index out of range]: IndexError: tuple index out of range
```

**Comment by engla** [comment]
Eh ok that's not so good, the problem is not one bad plugin but nothing in truncate code is working. Thanks a lot for testing!

**Comment by dcelasun** [comment]
No worries, let me know if I can help with testing.

**Comment by engla** [comment]
Can you still enable one of the failed plugins even with this?

**Comment by engla** [comment]
In that case I'd be grateful if you ran `kupfer --debug > output.log 2>&1` with the commit in branch debug-load

**Comment by engla** [comment]
I don't have python 3.6 to test with right now unfortunately (py 3.5 only)

**Comment by engla** [comment]
Run that, then open prefs window, quit and give me the file using gist.github.com is good.

**Comment by dcelasun** [comment]
OK, this is very weird. A lot of the plugins look duplicated, but when I click on the duplicates ("Core" below) they are different things. Logs are [here](https://gist.github.com/dcelasun/7d331af8ac831550d2733630b8eb320d).

![kupfer_plugins](https://cloud.githubusercontent.com/assets/144373/22646984/519aabc4-ec6f-11e6-8fd8-50873acc1474.png)
![kupfer_core_1](https://cloud.githubusercontent.com/assets/144373/22646986/54551868-ec6f-11e6-8700-09f41dc32455.png)
![kupfer_core_2](https://cloud.githubusercontent.com/assets/144373/22646988/56908fa4-ec6f-11e6-9d39-3d53a22ee96b.png)

**Comment by engla** [comment]
Ensure that you are not installing this over an old kupfer install. Needs to remove the old and install the new. Also clear out any user-installed plugins for now, I'd say. I don't know if the duplication is that. I found that py 3.6 does some changes to their opcodes, and it's time to move off the insane truncate_code thing anyway.

**Comment by dcelasun** [comment]
I removed kupfer before installing v300 and deleted `~/.config/kupfer` and `~/.cache/kupfer`, so I don't think it's related to that.

**Comment by engla** [comment]
Ok! I've rewritten the "fake" plugin loading (for disabled plugins in the list) And it should now work with Python 3.6. It's in master.

**Comment by dcelasun** [comment]
Now it's perfect! No more duplicates in the list and no errors in the console.

**Comment by engla** [comment]
Ok, I'll pack a new release. Write here if you find any more bugs before then. Thanks a lot for the help so far.
