### ISSUE TITLE
WAF: ./waf configure raise UnicodeDecodeError

### ISSUE THREAD

**Issue by hugosenari** [kupferlauncher/kupfer#35]
In my system _./waf configure_ raise **UnicodeDecodeError**.

**Info**:
- System: ArchLinux 4.9.7-1
- Env: LANG=en_US.UTF-8, GDM_LANG=en_US.utf8
- Python: 3.6.0

**Stacktrace**:
```
Traceback (most recent call last):
  File "/home/hugosenari/codes/kupfer/waflib/Scripting.py", line 138, in waf_entry_point
    run_commands()
  File "/home/hugosenari/codes/kupfer/waflib/Scripting.py", line 225, in run_commands
    parse_options()
  File "/home/hugosenari/codes/kupfer/waflib/Scripting.py", line 186, in parse_options
    Context.create_context('options').execute()
  File "/home/hugosenari/codes/kupfer/waflib/Options.py", line 250, in execute
    super(OptionsContext, self).execute()
  File "/home/hugosenari/codes/kupfer/waflib/Context.py", line 213, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/hugosenari/codes/kupfer/waflib/Context.py", line 291, in recurse
    user_function(self)
  File "/home/hugosenari/codes/kupfer/wscript", line 115, in options
    opt.recurse(config_subdirs)
  File "/home/hugosenari/codes/kupfer/waflib/Context.py", line 285, in recurse
    wscript_module = load_module(node.abspath())
  File "/home/hugosenari/codes/kupfer/waflib/extras/compat15.py", line 111, in load_module
    ret = rev(path)
  File "/home/hugosenari/codes/kupfer/waflib/Context.py", line 539, in load_module
    code = Utils.readf(path, m='rU')
  File "/home/hugosenari/codes/kupfer/waflib/Utils.py", line 137, in readf
    return f.read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 207: ordinal not in range(128)
```

**Workaround**:
- Add fallback to read as utf8
```python
def readf(fname, m='r'):
    try:
        f = open(fname, m)
        txt = f.read()
    except UnicodeDecodeError:
        f.close()
        f = open(fname, m, encoding='utf-8')
        txt = f.read()
    finally:
        f.close()
    return txt
```

**Comment by bluss** [comment]
Which file is it reading? I'd like to fix this without patching waf

**Comment by bluss** [comment]
Can you tell me more about your locale environment? Do you have `en_US.UTF-8` generated?

**Comment by bluss** [comment]
I have reproduced the traceback and it indicates you don't actually have `en_US.UTF-8` as a generated locale (is it in the list `locale -a`?). If the locale does not exist, then this is not a bug, just simply an unsupported configuration.

**Comment by bluss** [comment]
Fixed by sticking to ascii in `wscript` files. That's probably best for compatibility.

The note about locales is true for kupfer too. Only supported use is locales that are actually generated and present for the LANG= (and related) environment.

**Comment by bluss** [comment]
Fortunately there is ongoing work in all kinds of corners to make the fallback locale use utf-8 as well.

https://sourceware.org/glibc/wiki/Proposals/C.UTF-8
https://www.python.org/dev/peps/pep-0538/

**Comment by hugosenari** [comment]
Hi,
Excuse not answered before. =)
```
~> locale -a
C
POSIX
en_US.utf8
pt_BR.utf8
```

I hope that someone somewhere someday fix this globally. But I'm not expecting this to be true in less than 3 years (2 more to spread). ;)

Thank you.
