### ISSUE TITLE
Trash plugin crashes in Kupfer

### ISSUE THREAD

**Issue by SanskritFritz** [kupferlauncher/kupfer#52]
Kupfer Version: v311
Window Manager: kwin
Desktop Environment: Plasma desktop 5.8.5
Linux Distribution: Arch Linux

There is no traces of Trash in the menu, only when I search for a file, then there is "Move to Trash" but it doesn't do anything.

Shell output:
```Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/kupfer/kupfer/core/sources.py", line 77, in rescan_source
    list(source.get_leaves(force_update=force_update))
  File "/usr/share/kupfer/kupfer/obj/base.py", line 426, in get_leaves
    self.cached_items = aslist(sort_func(self.get_items_forced()))
  File "/usr/share/kupfer/kupfer/obj/base.py", line 158, in aslist
    seq = list(seq)
  File "/usr/share/kupfer/kupfer/plugin/trash.py", line 201, in get_items
    yield Trash(TRASH_URI)
  File "/usr/share/kupfer/kupfer/plugin/trash.py", line 165, in __init__
    SpecialLocation.__init__(self, trash_uri, name=name)
  File "/usr/share/kupfer/kupfer/plugin/trash.py", line 148, in __init__
    Gio.FileQueryInfoFlags.NONE, None)
GLib.GError: g-io-error-quark: Operation not supported (15)```

**Comment by bluss** [comment]
Thanks. This is not a regression, right? I suspect it simply needs gvfs, but I'm not sure. It should have more error checking, but since Kupfer is built on top of the G-technologies like GLib, Gio, Gtk, I'm not sure we can be without gvfs as a real dependency.

**Comment by bluss** [comment]
Remaining issue is how to check better for presence of gvfs. I suppose it is ok if it's not a mandatory dep.

**Comment by SanskritFritz** [comment]
Thanks, that was the problem indeed. Installing gvfs led me to another error
```GLib.Error: g-io-error-quark: Unable to trash file /home/frank/abevjava_frank.log across filesystem boundaries (15)```
but I think this is not kupfer's problem.

**Comment by bluss** [comment]
Right. Kupfer should report that as a nice user visible error. Focusing on quality of existing features like that is important (but a lot to do).
